/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("POsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThePOsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThePOsList.onFilterBar().iCheckFilterField("{i18n>po_id}");
            Then.onThePOsList.onFilterBar().iCheckFilterField("{i18n>gross_amount}");
            Then.onThePOsList.onFilterBar().iCheckFilterField("Supplier");
            Then.onThePOsList.onFilterBar().iCheckFilterField("{i18n>overall_status}");
            Then.onThePOsList.onFilterBar().iCheckFilterField("{i18n>currency_code}");
            Then.onThePOsList.onFilterBar().iCheckFilterField("{i18n>supplier_name}");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onThePOsList.onFilterBar().iChangeSearchField("Search Term");
        //     When.onThePOsList.onFilterBar().iExecuteSearch();
        //     Then.onThePOsList.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThePOsList.onTable().iCheckColumns(undefined, {"3":{"header":"Boost"},"PO_ID":{"header":"{i18n>po_id}"},"GROSS_AMOUNT":{"header":"{i18n>gross_amount}"},"OVERALL_STATUS":{"header":"{i18n>overall_status}"},"PARTNER_GUID/COMPANY_NAME":{"header":"{i18n>company_name}"},"CURRENCY_code":{"header":"{i18n>currency_code}"},"TAX_AMOUNT":{"header":"{i18n>tax_amount}"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onThePOsList.onFilterBar().iExecuteSearch();
            
            Then.onThePOsList.onTable().iCheckRows();

            When.onThePOsList.onTable().iPressRow(0);
            Then.onThePOsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});