/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PurchaseOrderItemsObjectPageObjectPage journey");

        opaTest("Navigate to PurchaseOrderItemsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onThePOsList.onFilterBar().iExecuteSearch();

            Then.onThePOsList.onTable().iCheckRows();
            When.onThePOsList.onTable().iPressRow(0);

            Then.onThePOsObjectPage.iSeeThisPage();
            Then.onThePOsObjectPage.onTable({ property: "Items" }).iCheckRows();
            When.onThePOsObjectPage.onTable({ property: "Items" }).iPressRow(0);

            Then.onThePurchaseOrderItemsObjectPage.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThePurchaseOrderItemsObjectPage.iCheckNumberOfSections(2);
            When.onThePurchaseOrderItemsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::LineItemHeader");
            Then.onThePurchaseOrderItemsObjectPage.iCheckSection({ section: "FieldGroup::LineItemHeader" });
            Then.onThePurchaseOrderItemsObjectPage.onForm({ section: "FieldGroup::LineItemHeader" }).iCheckField({ property: "PO_ITEM_POS" });
            Then.onThePurchaseOrderItemsObjectPage.onForm({ section: "FieldGroup::LineItemHeader" }).iCheckField({ property: "PRODUCT_GUID_NODE_KEY" });
            Then.onThePurchaseOrderItemsObjectPage.onForm({ section: "FieldGroup::LineItemHeader" }).iCheckField({ property: "GROSS_AMOUNT" });
            Then.onThePurchaseOrderItemsObjectPage.onForm({ section: "FieldGroup::LineItemHeader" }).iCheckField({ property: "NET_AMOUNT" });
            Then.onThePurchaseOrderItemsObjectPage.onForm({ section: "FieldGroup::LineItemHeader" }).iCheckField({ property: "TAX_AMOUNT" });
            Then.onThePurchaseOrderItemsObjectPage.onForm({ section: "FieldGroup::LineItemHeader" }).iCheckField({ property: "CURRENCY_code" });
            When.onThePurchaseOrderItemsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::ProductDetails");
            Then.onThePurchaseOrderItemsObjectPage.iCheckSection({ section: "FieldGroup::ProductDetails" });
            Then.onThePurchaseOrderItemsObjectPage.onForm({ section: "FieldGroup::ProductDetails" }).iCheckField({ property: "PRODUCT_GUID/PRODUCT_ID" });
            Then.onThePurchaseOrderItemsObjectPage.onForm({ section: "FieldGroup::ProductDetails" }).iCheckField({ property: "PRODUCT_GUID/DESCRIPTION" });
            Then.onThePurchaseOrderItemsObjectPage.onForm({ section: "FieldGroup::ProductDetails" }).iCheckField({ property: "PRODUCT_GUID/CATEGORY" });
            Then.onThePurchaseOrderItemsObjectPage.onForm({ section: "FieldGroup::ProductDetails" }).iCheckField({ property: "PRODUCT_GUID/SUPPLIER_GUID/COMPANY_NAME" });
            Then.onThePurchaseOrderItemsObjectPage.onForm({ section: "FieldGroup::ProductDetails" }).iCheckField({ property: "PRODUCT_GUID/TAX_TARIF_CODE" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});